---
- name: Install Java 17 (Amazon Corretto)
  yum:
    name: java-17-amazon-corretto-devel
    state: present

- name: Add Elasticsearch YUM repo
  copy:
    dest: /etc/yum.repos.d/elasticsearch.repo
    content: |
      [elasticsearch]
      name=Elasticsearch repository for 9.x packages
      baseurl={{ elastic_repo_url }}
      gpgcheck=1
      gpgkey={{ elastic_gpg_key }}
      enabled=0
      type=rpm-md

- name: Install Elasticsearch
  dnf:
    name: elasticsearch
    enablerepo: elasticsearch
    state: present

- name: Configure Elasticsearch
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: root
    mode: '0644'
  notify: restart elasticsearch

- name: Enable and start Elasticsearch service
  systemd:
    name: elasticsearch
    enabled: true
    state: started
