---
- name: Add Elasticsearch YUM repository
  yum_repository:
    name: elasticsearch
    description: "Elasticsearch repository for 9.x packages"
    baseurl: "{{ elasticsearch_repo_url }}"
    gpgcheck: yes
    gpgkey: "{{ elasticsearch_gpg_key }}"
    enabled: yes

- name: Install Elasticsearch
  yum:
    name: elasticsearch
    state: present

- name: Clean up invalid sysconfig entries
  lineinfile:
    path: /etc/sysconfig/elasticsearch
    regex: "^(discovery\\.type|xpack\\.security\\.enabled)="
    state: absent

- name: Set heap size via sysconfig (simplest method)
  lineinfile:
    path: /etc/sysconfig/elasticsearch
    regex: "^ES_JAVA_OPTS="
    line: 'ES_JAVA_OPTS="-Xms{{ elasticsearch_heap_size }} -Xmx{{ elasticsearch_heap_size }}"'
    create: yes
  notify: Restart Elasticsearch

- name: Configure elasticsearch.yml
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: '0640'
  notify: Restart Elasticsearch

- name: Ensure Elasticsearch service is enabled and started
  systemd:
    name: elasticsearch
    enabled: yes
    state: started