---
- name: Add Elasticsearch YUM repository
  yum_repository:
    name: elasticsearch
    description: "Elasticsearch repository for 9.x packages"
    baseurl: "{{ elasticsearch_repo_url }}"
    gpgcheck: yes
    gpgkey: "{{ elasticsearch_gpg_key }}"
    enabled: yes

- name: Install Elasticsearch
  yum:
    name: elasticsearch
    state: present

- name: Configure elasticsearch.yml
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: '0640'
  notify: Restart Elasticsearch

- name: Set JVM heap size
  lineinfile:
    path: /etc/elasticsearch/jvm.options.d/heap.options
    create: yes
    line: "-Xms{{ elasticsearch_heap_size }}"
  notify: Restart Elasticsearch

- name: Ensure Elasticsearch service is enabled and started
  systemd:
    name: elasticsearch
    enabled: yes
    state: started
