---
- name: Add Elasticsearch YUM repository
  ansible.builtin.yum_repository:
    name: "{{ es_rpm_repo_name }}"
    description: "{{ es_rpm_repo_description }}"
    baseurl: "{{ es_rpm_repo_baseurl }}"
    gpgkey: "{{ es_rpm_repo_gpgkey }}"
    enabled: "{{ (es_rpm_repo_enabled | bool) | ternary(1,0) }}"
    gpgcheck: 1

- name: Install Elasticsearch (enable repo for this install)
  ansible.builtin.dnf:
    name: elasticsearch
    enablerepo: "{{ es_rpm_repo_name }}"
    state: present
  notify: restart elasticsearch

- name: Template elasticsearch.yml
  ansible.builtin.template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: elasticsearch
    group: elasticsearch
    mode: '0644'
  notify: restart elasticsearch

- name: Configure environment variables for systemd
  ansible.builtin.copy:
    dest: /etc/sysconfig/elasticsearch
    content: |
      {% for key, val in es_env_vars.items() %}
      {{ key }}={{ val }}
      {% endfor %}
    owner: root
    group: root
    mode: '0644'
  notify: restart elasticsearch

- name: Enable and start Elasticsearch service
  ansible.builtin.systemd:
    name: elasticsearch
    enabled: true
    state: started
