---
- name: Install Java
  yum:
    name: "{{ java_package }}"
    state: present
- name: Create backend user
  user:
    name: "{{ app_user }}"
    shell: "{{ app_shell }}"
    create_home: no
- name: Create /app directory with SGID
  file:
    path: /app
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '2775'   # SGID bit set (2 before 775)

- name: Ensure default ACL for group ownership
  acl:
    path: /app
    entity: "{{ app_user }}"
    etype: group
    permissions: rwx
    default: yes
    state: present

