---
- name: Install Java
  yum:
    name: "{{ java_package }}"
    state: present
- name: Create backend user
  user:
    name: "{{ app_user }}"
    shell: "{{ app_shell }}"
    create_home: no
- name: Create app directory
  file:
    path: "{{ app_dir }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0755'
