---
- name: Install Nginx, Git and curl
  package:
    name:
      - nginx
    state: present

- name: Enable and start Nginx
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Clear existing Nginx HTML folder
  file:
    path: "{{ nginx_html_dir }}"
    state: directory
    recurse: yes
  