---
- name: Install Nginx, Git and curl
  package:
    name:
      - nginx
    state: present

- name: Enable and start Nginx
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Remove all files in /usr/share/nginx/html
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "/usr/share/nginx/html/*"
  