---
- name: Add Kibana YUM repository
  template:
    src: kibana.repo.j2
    dest: /etc/yum.repos.d/kibana.repo
    owner: root
    group: root
    mode: '0644'

- name: Install Kibana
  dnf:
    name: kibana
    state: present

- name: Deploy Kibana configuration
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: root
    group: kibana
    mode: '0640'
  notify: restart kibana

- name: Reload systemd daemon
  command: systemctl daemon-reload
  notify: restart kibana

- name: Enable and start Kibana service
  systemd:
    name: kibana
    enabled: true
    state: started
