---
- name: Install necessary tools
  package:
    name:
      - awscli
      - jq
    state: present

- name: Fetch secrets from AWS Secrets Manager
  command: >
    aws secretsmanager get-secret-value
    --secret-id {{ secret_name }}
    --query SecretString
    --output text
  register: secrets_raw

- name: Parse DB_USER and DB_PASSWORD
  set_fact:
    db_user: "{{ secrets_raw.stdout | from_json | json_query('DB_USER') }}"
    db_password: "{{ secrets_raw.stdout | from_json | json_query('DB_PASSWORD') }}"

- name: Fetch DB_HOST from SSM
  command: >
    aws ssm get-parameter
    --name {{ db_host_param }}
    --with-decryption
    --query "Parameter.Value"
    --output text
  register: db_host_raw

- name: Fetch DB_NAME from SSM
  command: >
    aws ssm get-parameter
    --name {{ db_name_param }}
    --with-decryption
    --query "Parameter.Value"
    --output text
  register: db_name_raw

- name: Fetch REDIS_HOST from SSM
  command: >
    aws ssm get-parameter
    --name {{ redis_host_param }}
    --with-decryption
    --query "Parameter.Value"
    --output text
  register: redis_host_raw

- name: Set facts for SSM parameters
  set_fact:
    db_host: "{{ db_host_raw.stdout }}"
    db_name: "{{ db_name_raw.stdout }}"
    redis_host: "{{ redis_host_raw.stdout }}"

- name: Generate systemd service file
  template:
    src: backend.service.j2
    dest: "{{ service_file }}"
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable and start backend service
  systemd:
    name: backend
    enabled: yes
    state: started
